### PR TITLE
feat: pnpm package manager implementation to improve dependency installation

### PR DESCRIPTION
**Pull request by xelacast**
## ✅ Checklist

- [x] The PR title follows the conventions in [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

## Changelog

When I cloned this app and followed the setup I noticed the npm package manager was extremely slow when installing the dependencies. I updated the repo with the pnpm package manager. This improved installation times from 2 1/2 minutes down to 7 seconds.

- Added .npmrc in main folder and to the flowtest-electron  folder to work with electron configuration and pnpm
- Removed the package-lock from the .gitignore to improve dependency installation times
- The initial pnpm download added a pnpm-lock.yaml file. This will improve dependency download times for future developer contributions
- Updated package.json files to reflect pnpm changes
- Updated README.md setup instructions to reflect pnpm changes

### CODE REVIEW

**Comment by jsajal** [comment]
@xelacast thanks for doing this. I always wanted to experiment with `pnpm` but never got the time.
this lgtm with one comment

```
sjain@Sajals-MacBook-Pro FlowTest % pnpm install              
 ERR_PNPM_BAD_PM_VERSION  This project is configured to use v9.0.4 of pnpm. Your current pnpm is v9.0.6

If you want to bypass this version check, you can set the "package-manager-strict" configuration to "false" or set the "COREPACK_ENABLE_STRICT" environment variable to "0"
```

I faced this problem when going through the steps, so either we need to mention `npm install -g pnpm@9.0.4` in the step or removed version name in `"packageManager": "pnpm@9.0.4"`

`npm install -g pnpm` by default installs the latest version which is `9.0.6`

**Comment by xelacast** [comment]
@jsajal thank you for the update 🤝. I looked into this and didn't fully understand corepack until now. It doesn't allow backward/forward capability with pnpm but pnpm docs insist on using it. 

I'm going to put the exact pnpm version in the npm install and readme. I updated the pnpm version in the package.json. There is a way to schedule a bot to update the README and package.json files with a PR when new versions are released using (Renovate)[https://docs.renovatebot.com], I'll look into that.

**Comment by jsajal** [comment]
@xelacast is there a reason we are specifying a specific version of `pnpm`. Why not leave it as just `npm install -g pnpm`? just like `node` this will install the latest version of `pnpm` and users should be good.

**Comment by xelacast** [comment]
I was thinking the same but if pnpm updates before we bump the version in the package manager ourselves it'll result in the ERR_PNPM_BAD_PM_VERSION error. Not a terrible thing but we would have to stay up to date on pnpm upgrades. 

My thought for now is to change the pnpm version in the readme.md anytime we bump the pnpm version in package.json. We could use a bot to make a pr for the bump and then change the README.md to ```npm install pnpm``` to make it easier in the future.

**Review by jsajal — APPROVED** [review]
lgtm, thanks for this!

**Comment by xelacast** [comment]
I'm glad I could help!

**Pull request merged**
